
site:
  name:
    class: img 
    custom: /img/site/favicon.svg
  icon: /img/site/favicon.png # Site icon / 网站图标
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Navigation bar
# 导航栏
nav:
  # Left Box
  # 左侧盒子
  group:
  #  project: # name
  #    Solitude: https://github.com/everfu/hexo-theme-solitude || /img/pwa/favicon.ico # name: url || icon

  # Menu
  # 菜单
  menu:
    # 首页: / # name: link
    # 文章: # name
    #   归档: /archives/ || fas fa-folder-closed # item name: link || icon
    #   分类: /categories/ || fas fa-clone
    #   标签: /tags/ || fas fa-tags
    # 友链:
    #   朋友圈: /moments/ || fas fa-wifi
    #   友情链接: /links/ || fas fa-user-group
    #   宝藏博主: javascript:travelling() || fas fa-gift
    # 我的:
    #   关于: /about/ || fas fa-user
    #   装备: /kit/ || fas fa-laptop
    #   音乐馆: /music/ || fas fa-music

  # Right button
  # 右侧按钮
  right:
    random: false # Random article / 随机文章按钮
    custom:
    #  - name: 开往 # 名字
    #    url: https://www.travellings.cn/go.html # 跳转链接
    #    icon: fas fa-train # 图标
    #    onclick: # 点击事件
    #    id: travellings_button # id
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Home Top Banner
# 首页顶部
hometop:
  enable: false
  banner:
    title: 分享技术<br >与科技生活 # 大字
    desc:
      一个热爱生活的人 # 小字
      # - 我只是一个普通的程序员
      # - 但我有一个不平凡的梦想
      # - 我希望能够改变世界
    icon:
      # HTML: # name
      #   img: https://i.postimg.cc/vBWVnY8q/html.png # url
      #   color: "#e9572b" # color
      # JS:
      #   img: https://i.postimg.cc/3N10Ltv2/js.png
      #   color: "#f7cb4f"
      # Docker:
      #   img: https://i.postimg.cc/8Pk6Fg24/docker.png
      #   color: "#57b6e6"
      # Flutter:
      #   img: https://i.postimg.cc/hPC7T3gB/flutter.png
      #   color: "#ffffff"
      # WebPack:
      #   img: https://i.postimg.cc/dVLZBmtT/webpack.png
      #   color: "#2e3a41"
      # Git:
      #   img: https://i.postimg.cc/nhgjwjCS/git.png
      #   color: "#df5b40"
  group:
    # 热门: /tags/Fire/ || fas fa-fire || linear-gradient(to right,#f65,#ffbf37)
  recommendList:
    enable: false
    sup: 置顶
    title: Solitude 官方文档
    url: https://solitude.js.org/
    img: /img/default.avif
    color: "none"
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Aside
# 侧边栏
aside:
  # Values: about (info card), newestPost (latest article), allInfo (website information), newest_comment (latest comment)
  # 值: about(信息卡), newestPost(最新文章), allInfo(网站信息), newest_comment(最新评论)

  # Sticky: Fixed position / noSticky: Not fixed position
  # Sticky: 固定位置 / noSticky: 不固定位置
  home: # on the homepage
    noSticky: "about"
    Sticky: "allInfo"
  post: # on the article page
    noSticky: "about"
    Sticky: "newestPost"
  page: # on the page
    noSticky: "about"
    Sticky: "newestPost,allInfo"
  # 菜单栏位置(0: 左 1: 右)
  position: 1 # Sidebar positioning(0: left 1: right)

  # --------------------------- start ---------------------------
  # Information card
  # 信息卡
  my_card:
    author:
      img: /img/logo.png # url
      sticker: # url, 24x24 size
    # 介绍 / Introduction
    description: 只有迎风，风筝才能飞得更高。
    # 内容 / Content
    content: # 这是我的博客 / This is my Blog
    state:
      morning: ✨ 早上好，新的一天开始了
      noon: 🍲 午餐时间
      afternoon: 🌞 下午好
      night: 早点休息
      goodnight: 晚安 😴
    witty_words:
      # - 你可以的
      # - 你一定可以的
      # - 祝你好运，陌生人
    # social
    # 社交信息图标
    information:
    #  Github: https://github.com/everfu || fab fa-github # Name: link || icon
    #  Bilibili: https://space.bilibili.com/1329819902 || fab fa-bilibili
  # --------------------------- end ---------------------------

  # --------------------------- start ---------------------------
  # article table of contents
  # 文章目录
  toc:
    post: true
    page: false
    vague: true
  # --------------------------- end ---------------------------

  # --------------------------- start ---------------------------
  # Tags
  # 标签
  tags:
    enable: false
    limit: 20 # Number of tags displayed
    # Highlighted tags
    highlight_list:
      # - Hexo
  # --------------------------- end ---------------------------

  # --------------------------- start ---------------------------
  # Site Info
  # 网站信息
  siteinfo:
    # Number of articles
    # 文章数量
    postcount: true
    # Total number of words
    # 总字数
    wordcount: false
    # PV
    pv: true
    # UV
    uv: true
    # Last update date
    # 最后更新日期
    updatetime: true
    # Website creation time
    # 网站创建时间
    runtimeenable: true
    # Format: yyyy-MM-dd hh-mm-ss
    # 格式: yyyy-MM-dd hh-mm-ss
    runtime: "2023-04-20 00:00:00"
  # --------------------------- end ---------------------------
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Page default settings
# 页面默认设置
page:
  # 404 page
  # 404 页面
  error: true
  # Tags page
  # 标签页面
  tags: true
  # Categories page
  # 分类页面
  categories: true
  # list: Sort List / 1: Follow HomeList
  # list: 排序列表 / 1: 跟随首页列表
  archives: 0
  # Default value
  # 默认值
  default:
    # Default image when no cover is set
    # 未设置封面时的默认图片
    cover:
      # - /img/default.png # 默认图片 / default cover
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Post default settings
# 文章默认设置
post:
  default:
    # Default image when no cover is set
    # 未设置封面时的默认图片
    cover:
      # - /img/default.avif # 默认图片 / default cover
    # Location
    # 位置
    locate: China
    # Copyright
    # 版权
    copyright:
      enable: true
      author: /img/logo.png # url
      # License
      # 许可证
      license: CC BY-NC-SA 4.0
      # License link
      # 许可证链接
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans
  # Article Local AI
  # 文章本地AI
  ai:
    enable: false
    modelName: 小七 GPT
  # Article meta information
  # 文章元信息
  meta:
    # Release date
    # 发布日期
    date: false
    # Update date
    # 更新日期
    updated: false
    # Location
    # 位置
    locate: false
    # Number of words
    # 字数
    wordcount: false
    # uv
    readtime: false
    # pv
    pv: false
    # Comment count
    # 评论数
    comment: false
  # Reward
  # 打赏
  award:
    enable: false
    appreciators: /about/ # Reward page
    # Reward Title
    # 打赏标题
    title: # Thanks for your appreciation. / 感谢您的赞赏
    desc: # Because of your support, I realize the value of writing articles. / 由于您的支持，我才能够实现写作的价值。
    # Reward list
    # 打赏列表
    list:
      # - name: Github Sponsor
      #   qcode: https://s3.qjqq.cn/47/661ba900c4bc1.webp!color
      #   url: https://github.com/sponsors/everfu
      #   color: var(--efu-black)

  # Share icon
  # 分享图标
  share:
    enable: false
    list:
      # - qq
      # - weibo
      # - twitter
      # - facebook
      # - telegram
      # - whatsapp
      # - linkedin
      # - link
      # - qrcode
  rss: # /atom.xml
  # Article reading progress
  # 文章封面取色
  covercolor:
    enable: false
    # local: local color / api: api color / ave: oss average color
    mode: local
    # api address / api 地址
    api: https://api.qjqq.cn/api/Imgcolor?img=
    # Storage / 缓存时间
    time: 43200000
  footer:
    enable: false
    desc: # Articles from Ever Fu. / 文章来自 Ever Fu # description
    button: # Button
      enable: true
      name: # Learn more / 了解更多
      url: /about/
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Custom Theme Color
theme_color:
  dark: "#ffc848" # dark
  light: "#425AEF" # light
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# display mode
# 显示模式
display_mode:
  # auto: automatic switching(Recognize the current theme mode of the device) / dark: dark mode / light: light mode
  # auto: 自动切换（识别设备当前主题模式） / dark: 深色模式 / light: 浅色模式
  type: auto
  # After opening, the dark mode will display the starry sky background
  # 开启后深色模式会显示星空背景
  universe: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Font
# 字体
font:
  font-size: 16px
  code-font-size: 16px
  # Global font
  # 全局字体
  font-family: "PingFang SC, Hiragino Sans GB, Microsoft YaHei, sans-serif"
  # Code font
  # 代码字体
  code-font-family: '"monospace", monospace'
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Lure
# When the user exits the page, modify the title
# 当用户退出页面时，修改标题
lure:
  enable: false
  jump: 404 Not Found
  back: ヾ(≧∇≦*)ゝHey, hey, you fell for it.
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Article expiration
# 文章过期
expire:
  enable: false
  time: 30 # days
  position: top # top / bottom
  text_prev: "This article expired "
  text_next: " day ago, if the content does not match, please contact the webmaster to update it."
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Home page article configuration information
# 首页文章配置信息
index_post_list:
  direction: column # row / column
  column: 2 # 2: 2 columns 3: 3 columns
  cover: both
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Related articles
# 相关文章
related_post:
  enable: false
  limit: 2
  # created: release date / updated: update date
  # created: 发布日期 / updated: 更新日期
  date_type: created
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Custom right menu
# 自定义右键菜单
right_menu:
  enable: false
  # Whether to display the hot comment switch.
  # 是否显示热门评论开关
  commentBarrage: false
  # Whether to display the browser's context menu when hold Ctrl key.
  # 是否在按住 Ctrl 键时显示浏览器右键菜单
  ctrlOriginalMenu: false
  # Simplified and Traditional Chinese translation.
  # 简繁体转换
  translate: false
  # Custom list
  # 自定义列表
  custom_list:
    # - name: 随机文章
    #   click: toRandomPost()
    #   id: menu-randomPost
    #   class:
    #   icon: fas fa-tower-broadcast
    # - name: 全部分类
    #   click: pjax.loadUrl('/categories/') # External links with window.open, pjax can not request cross-domain content.
    #   id:
    #   class:
    #   icon: fas fa-clone
    # - name: 全部标签
    #   click: pjax.loadUrl('/tags/')
    #   id:
    #   class:
    #   icon: fas fa-tags
# --------------------------- end -----------------------

# --------------------------- start ---------------------------
# Copy
#  information
# 复制信息
copy:
  enable: false
  # Turn on Link copyright information after copying.
  # 复制后链接版权信息
  copyright:
    enable: false
    # Display when the number of words copied exceeds
    # 复制文字时超过多少字数显示
    limit: 50
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Mermaid
mermaid: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Chart.js
chart: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# typeit
typeit: false
# --------------------------- end ---------------------------

### Extended configuration

# --------------------------- start ---------------------------
# Console
# 控制台
console:
  enable: false
  # Recent comments
  # 最新评论
  recentComment:
    enable: false
    # Cache time 1: 1 day / .5 : half a day
    # 缓存时间 1: 1天 / .5 : 半天
    storage: .2
  card:
    # Tags
    # 标签
    tags: true
    # Archives
    # 归档
    archive: "month" # month: by month / year: by year
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
translate:
  enable: true
  defaultEncoding: 2 # 1: 默认繁体 2: 默认简体
  translateDelay: 0 # 首次加载翻译迟疑时间
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Right-Sidebar
# 右下角悬停导航栏
rightside:
  enable: false
  percent: false
  hide:
    enable: false
    translate: false
    mode: false
    aside: false
# --------------------------- start ---------------------------

# --------------------------- start ---------------------------
# Footer
# 页脚
footer:
  # 社交图标
  information:
    author: false # img url / false
    left:
      # Github: https://github.com/everfu || fab fa-github # 名称: 链接 || 图标
      # Mail: mailto:o@everfu.org || far fa-envelope
    right:
      # Bilibili: https://space.bilibili.com/1329819902 || fab fa-bilibili
      # Douyin: https://v.douyin.com/iJsLc8jt/ || fab fa-tiktok
  # 友情链接
  group:
    # 导航:
    #   Archives: /archives/
    #   Categories: /categories/
    #   Tags: /tags/
    # 排列:
    #   Cookies: /cookies/
    #   Privacy: /privacy/
    #   Copyright: /copyright/

  # 随机友链
  randomlink: false # 随机友链

  # 备案
  beian:
    # - name: 湘公网安备43048102000175号
    #   icon: https://beian.mps.gov.cn/img/logo01.dd7ff50e.png
    #   url: https://beian.mps.gov.cn/#/query/webSearch
    # - name: 湘ICP备2024080357号-1
    #   url: https://beian.miit.gov.cn/

  # 页脚信息文字
  links:
    # - name: RSS
    #   url: /atom.xml
    # - name: License
    #   url: https://github.com/everfu/hexo-theme-solitude/blob/main/LICENSE
    #   icon:
    #     - fas fa-copyright
    #     - fab fa-creative-commons-by
    #     - fab fa-creative-commons-nc
    #     - fab fa-creative-commons-nd
    # - name: boringbay
    #   url: https://boringbay.com/
    #   img: https://boringbay.com/api/badge/www.efu.me
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 404 page
# 404 页面
errorpage:
  img: /img/404.avif
  text: =awa= Page Not Found # Text
  recommendList: true
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Meting API
# This part of the content uses metingjs,
# can only use NetEase Cloud Music, QQ Music and other music platforms supported by the mainland China region,
# the subsequent consideration of the use of JSON files to store music information and customize the implementation of the third-party API does not depend on the page.
# Music Page
meting_api: "https://meting.qjqq.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r" # Custom API
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Capsule music
# 音乐胶囊
capsule:
  enable: false
  # 歌单 ID / 单曲 ID
  id: 5144842535
  # 服务商：netease / qq / xiami / kugou / baidu
  server: netease
  # 类型：playlist / song
  type: playlist
  volume: 0.8
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Quick Menu
# Open with shift + ?
# 快捷菜单
# 使用 shift + ? 打开
keyboard:
  enable: false
  list:
    # - name: 关闭快捷菜单
    #   key: K
    #   func: keyboard
    # - name: 打开控制台
    #   key: A
    #   sco: showConsole
    # - name: 播放/暂停音乐
    #   key: M
    #   sco: musicToggle
    # - name: 打开友链
    #   key: L
    #   url: /links/
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Lazyload
# 懒加载
lazyload:
  enable: false
  field: site
  placeholder: ""
  errorimg: /img/error_load.avif
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Loading
# 加载
loading:
  # Full screen loading
  # 全屏加载
  fullpage: false
  # Loading icon, default is siteicon
  # 加载图标，不写默认siteicon
  favicon: /img/favicon.png
  # Pace loading
  # Pace 加载
  pace: true
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Highlight
# 代码块高亮
highlight:
  enable: true
  # Display the fold button when the number of words exceeds
  # 当超过多少字时显示折叠按钮
  limit: 200
  # Whether to enable the copy button
  # 是否启用复制按钮
  copy: true
  # Whether to expand by default
  # 是否默认展开
  expand: true
  # default: default / mac : apple terminal
  # default: 默认 / mac : 苹果终端
  theme: mac
  # default / solidity / dracula
  color: default
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Lightbox
# 图片灯箱
lightbox: false
# warning: Please select any one, but cannot be turned on at the same time.
# 警告: 请任选其一，但不能同时开启。
fancybox: false # fancybox
mediumZoom: false # mediumZoom
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Memorial
# Turn the entire site gray on memorable days.
# 在纪念日整个网站变灰
memorial:
  enable: false
  date:
  #  - 7-7
  #  - 9-18
  #  - 12-13
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# OpenGraph
OpenGraph:
  enable: false
  options:
    # twitter_card:
    # twitter_image:
    # twitter_id:
    # twitter_site:
    # google_plus:
    # fb_admins:
    # fb_app_id:
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Word count
# 字数统计
# warning: Please install the hexo-wordcount plugin first.
# 警告: 请先安装 hexo-wordcount 插件。
wordcount: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Katex
# Latex formula support
# Latex 公式支持
katex:
  enable: false
  # Whether to load on each page
  # 是否在每个页面加载
  per_page: false
  # Whether to enable copy formula
  # 是否启用复制公式
  copytex: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# verification
# 验证
verify_site:
  # - name: google-site-verification
  #   content: xxxxxx
  # - name: baidu-site-verification
  #   content: xxxxxxx
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Legacy CSS Prefix 
# CSS前缀配置
css_prefix: true
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Extend
# 扩展
extends:
  # Insert in head
  # 插入到 head
  head:
  #  - <script src="https://cdn.bootcdn.net/ajax/libs/pace/1.2.4/pace.min.js"></script>

  # Insert in body
  # 插入到 body
  body:
  #  - <script src="https://cdn.bootcdn.net/ajax/libs/pace/1.2.4/pace.min.js"></script>
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# PWA
# Progressive Web App
pwa:
  enable: false
  manifest: /manifest.json # manifest.json
  theme_color: "#006a73" # Theme color
  mask_icon: /img/pwa/favicon.png # Mask icon
  apple_touch_icon: /img/pwa/favicon.png # Apple touch icon
  bookmark_icon: /img/pwa/favicon.png # Bookmark icon
  favicon_32_32: /img/pwa/f